apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apr.fullname" . }}-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "apr.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: manager
  template:
    metadata:
      labels:
        {{- include "apr.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: manager
    spec:
      serviceAccountName: {{ include "apr.managerServiceAccountName" . }}
      securityContext:
        {{- toYaml .Values.manager.podSecurityContext | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: manager
          image: {{ include "apr.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/apr-manager"]
          args:
            - --metrics-bind-address={{ .Values.manager.metricsBindAddress }}
            - --health-probe-bind-address={{ .Values.manager.healthProbeBindAddress }}
            - --leader-elect={{ .Values.leaderElection.enabled }}
            - --archive-image={{ include "apr.image" . }}
            - --archive-runner-service-account={{ include "apr.runnerServiceAccountName" . }}
            - --zap-log-level={{ .Values.log.level }}
            {{- if .Values.log.development }}
            - --zap-devel
            {{- end }}
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: probes
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: probes
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: probes
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            {{- toYaml .Values.manager.containerSecurityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.manager.resources | nindent 12 }}
